/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Kasir;

import Kasir.nota;
import app.Koneksi;
import app.Login;
import app.UserProfile;
import java.awt.Frame;
import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class HalamanKasir extends javax.swing.JFrame {

    String path_gambar;
    UserProfile pr;

    /**
     * Creates new form HalamanKasir
     */
    public HalamanKasir() {
        initComponents();
    }

    public HalamanKasir(UserProfile Up, String path_gambar) {
        initComponents();
        this.pr = Up;
        this.path_gambar = path_gambar;
        name_login.setText(pr.getFullname());
        role_login.setText(pr.getLevel());
        setProfileImage();
        tabelset();

    }

    private void tabelset() {
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    private void setProfileImage() {
        if (path_gambar != null && !path_gambar.isEmpty()) {
            try {
                Icon iconPath = new ImageIcon(path_gambar);
                Image image = ((ImageIcon) iconPath).getImage();
                Image scaledImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                Icon scaledIcon = new ImageIcon(scaledImage);
                jLabel1.setIcon(scaledIcon);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Gagal memuat gambar.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Path gambar tidak valid.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name_login = new javax.swing.JLabel();
        role_login = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        uang = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 80));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total :");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rp. 0,-");

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel11.setText("Kembali :");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Rp. 0,-");

        jButton3.setBackground(new java.awt.Color(255, 51, 0));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Hapus");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12))
                .addContainerGap(847, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(703, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel12)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 13, 72, 73));

        name_login.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 16)); // NOI18N
        name_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_login.setText("jLabel1");
        jPanel2.add(name_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 28, 163, -1));

        role_login.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        role_login.setForeground(new java.awt.Color(255, 153, 255));
        role_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        role_login.setText("jLabel1");
        jPanel2.add(role_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 53, 163, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Uang :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 29, 81, 37));

        uang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uangActionPerformed(evt);
            }
        });
        uang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                uangKeyReleased(evt);
            }
        });
        jPanel2.add(uang, new org.netbeans.lib.awtextra.AbsoluteConstraints(685, 29, 203, 37));

        jButton2.setBackground(new java.awt.Color(0, 0, 204));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Checkout");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(894, 28, -1, 37));

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Produk", "Jumlah", "Harga", "Total"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Menu");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setText("Laporan Keuangan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem3.setText("RiwayatTransaksi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Setting");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("LogOut");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin logout?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            // Menutup halaman admin dan membuka halaman login jika pengguna memilih "Yes"
            this.setVisible(false);
            Login loginPage = new Login();
            loginPage.setVisible(true);
            loginPage.setExtendedState(Frame.MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setVisible(false);
        LaporanKeuangan lk = new LaporanKeuangan(this.pr, path_gambar);
        lk.setVisible(true);
        lk.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
        RiwayatTransaksi rt = new RiwayatTransaksi(this.pr, path_gambar);
        rt.setVisible(true);
        rt.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        removeProductFromCart();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String val = jTextField1.getText();
        try {
            if (!val.isEmpty()) {
                int bayar = Integer.parseInt(val); // Validasi input
                String TH = jLabel5.getText();
                String[] arrTH = TH.split(" ");
                int totalH = Integer.parseInt(arrTH[1]);

                if (bayar >= totalH) {
                    long sisa = bayar - totalH;
                    jLabel12.setText("Rp " + sisa);
                    enableCheckoutBtn(true);
                } else {
                    jLabel12.setText("Rp 0");
                    enableCheckoutBtn(false);
                }
            } else {
                jLabel12.setText("Rp 0");
                enableCheckoutBtn(false);
            }
        } catch (NumberFormatException e) {
            jLabel12.setText("Rp 0");
            enableCheckoutBtn(false);
        }

        String kode = jTextField1.getText();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        try (Connection K = Koneksi.Gas()) {
            String query = "SELECT id, product_name, product_price_s, product_stock FROM products WHERE product_code = ?";
            PreparedStatement ps = K.prepareStatement(query);
            ps.setString(1, kode);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String pName = rs.getString("product_name");
                double pPr = rs.getDouble("product_price_s");
                int availableStock = rs.getInt("product_stock");

                boolean exists = false;
                int rowIndex = -1;

                for (int i = 0; i < model.getRowCount(); i++) {
                    int currentId = Integer.parseInt(model.getValueAt(i, 0).toString());
                    if (currentId == id) {
                        exists = true;
                        rowIndex = i;
                        break;
                    }
                }

                if (exists) {
                    // Update kuantitas dan harga total jika stok mencukupi
                    int currentQty = Integer.parseInt(model.getValueAt(rowIndex, 2).toString());
                    int newQty = currentQty + 1;

                    if (newQty <= availableStock) {
                        model.setValueAt(newQty, rowIndex, 2); // Update kuantitas
                        model.setValueAt(newQty * pPr, rowIndex, 4); // Update total harga
                    } else {
                        JOptionPane.showMessageDialog(this, "Stok tidak mencukupi! Tersedia: " + availableStock);
                    }
                } else {
                    // Tambahkan produk baru jika stok tersedia
                    if (availableStock > 0) {
                        Object[] data = {id, pName, 1, pPr, pPr};
                        model.addRow(data);
                    } else {
                        JOptionPane.showMessageDialog(this, "Stok tidak tersedia untuk produk: " + pName);
                    }
                }
            }

            updateharga();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan database: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }

        // Tambahkan listener untuk perubahan tabel
        model.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();

            if (column == 2 && row >= 0) {
                try {
                    int qty = Integer.parseInt(jTable1.getValueAt(row, 2).toString());
                    double price = Double.parseDouble(jTable1.getValueAt(row, 3).toString());

                    // Cek stok dari database
                    try (Connection K = Koneksi.Gas()) {
                        String stockQuery = "SELECT product_stock FROM products WHERE id = ?";
                        PreparedStatement ps = K.prepareStatement(stockQuery);
                        ps.setInt(1, Integer.parseInt(jTable1.getValueAt(row, 0).toString()));
                        ResultSet rs = ps.executeQuery();

                        if (rs.next()) {
                            int availableStock = rs.getInt("product_stock");

                            if (qty > 0 && qty <= availableStock) {
                                jTable1.setValueAt(qty * price, row, 4); // Update total harga
                                updateharga();
                            } else if (qty > availableStock) {
                                JOptionPane.showMessageDialog(null, "Stok tidak mencukupi!");
                                jTable1.setValueAt(1, row, 2); // Reset ke nilai default
                            }
                        }
                    }

                } catch (NumberFormatException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Kuantitas tidak valid atau kesalahan database!");
                    jTable1.setValueAt(1, row, 2); // Reset ke nilai default
                }
            }
        });
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String val = jTextField1.getText();
        try {
            if (!val.isEmpty()) {
                // Validasi input
                int bayar = Integer.parseInt(val);

                // Mendapatkan nilai total harga
                String TH = jLabel5.getText();
                String[] arrTH = TH.split(" ");

                if (arrTH.length > 1) { // Pastikan format teks benar
                    int totalH = Integer.parseInt(arrTH[1]);

                    // Cek apakah pembayaran mencukupi
                    if (bayar >= totalH) {
                        long sisa = bayar - totalH;
                        jLabel12.setText("Rp " + sisa);
                        enableCheckoutBtn(true);
                    } else {
                        jLabel12.setText("Rp 0");
                        enableCheckoutBtn(false);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Format total harga tidak valid!", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                    jLabel12.setText("Rp 0");
                    enableCheckoutBtn(false);
                }
            } else {
                jLabel12.setText("Rp 0");
                enableCheckoutBtn(false);
            }
        } catch (NumberFormatException e) {
            jLabel12.setText("Rp 0");
            enableCheckoutBtn(false);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped

    }//GEN-LAST:event_jTextField1KeyTyped

    private void uangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uangActionPerformed

    }//GEN-LAST:event_uangActionPerformed

    private void uangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uangKeyReleased
        UangPembayaran();
    }//GEN-LAST:event_uangKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        checkout();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel name_login;
    private javax.swing.JLabel role_login;
    private javax.swing.JTextField uang;
    // End of variables declaration//GEN-END:variables
public void setLabelFullname(String fullname) {
        name_login.setText(fullname);
    }

    public void setLabelLevel(String level) {
        role_login.setText(level);
    }

    public void updateUser(UserProfile Up, String path_gambar) {
        this.pr = Up;
        this.path_gambar = path_gambar;
        name_login.setText(pr.getFullname());
        role_login.setText(pr.getLevel());
        setProfileImage();
    }

    private void updateharga() {
        try {
            double totalHarga = 0;
            int rowcount = jTable1.getRowCount();
            for (int i = 0; i < rowcount; i++) {
                double QTY = Double.parseDouble(jTable1.getValueAt(i, 2).toString());
                double PRC = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
                totalHarga += (QTY * PRC);
            }
            jLabel5.setText("Rp " + (long) totalHarga);
        } catch (NumberFormatException e) {
        }
    }

    private void removeProductFromCart() {
        int idx = jTable1.getSelectedRow();
        if (idx != -1) {
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            m.removeRow(idx);
            updateharga();
        } else {
            JOptionPane.showMessageDialog(this, "Anda belum memilihi data");
        }
    }

    private void UangPembayaran() {
        int r = jTable1.getRowCount();
        if (r > 0) {
            String lbl = jLabel5.getText(); //Rp 12000
            String[] arrayHarga = lbl.split(" ");
            long harga = Long.parseLong(arrayHarga[1]);

            String bayar = uang.getText();
            if (!bayar.isEmpty()) {
                long uangbayar = Long.parseLong(bayar);
                long uangkembali = uangbayar - harga;
                jLabel12.setText("Rp " + uangkembali);

                if (uangbayar >= harga) {
                    jButton2.setEnabled(true);
                } else {
                    jButton2.setEnabled(false);
                }
            } else {
                jLabel12.setText("Rp " + 0);
                jButton2.setEnabled(false);
            }
        }
    }

    private void enableCheckoutBtn(boolean b) {
        jButton2.setEnabled(b);
    }

    private void checkout() {
        Connection K = null;
        PreparedStatement insertTransaksi = null;
        PreparedStatement insertDetailTransaksi = null;
        PreparedStatement updateStok = null;
        String uangKembali = jLabel12.getText(); // Uang kembalian dari GUI
        String uangPembayaran = uang.getText();  // Uang pembayaran dari GUI

        try {
            // Mulai koneksi dan nonaktifkan auto-commit
            K = Koneksi.Gas();
            K.setAutoCommit(false);

            // Ambil tanggal transaksi
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String tanggalTransaksi = sdf.format(new Date());

            // Data kasir
            int idKasir = pr.getId();

            // Hitung total harga dari keranjang
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            double totalTransaksi = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                double harga = Double.parseDouble(model.getValueAt(i, 3).toString());
                totalTransaksi += qty * harga;
            }

            // Masukkan data ke tabel transaksi
            String insertTransaksiQuery = "INSERT INTO transaksi (id_akun, tanggal_transaksi, total_harga) VALUES (?, ?, ?)";
            insertTransaksi = K.prepareStatement(insertTransaksiQuery, Statement.RETURN_GENERATED_KEYS);
            insertTransaksi.setInt(1, idKasir);
            insertTransaksi.setString(2, tanggalTransaksi);
            insertTransaksi.setDouble(3, totalTransaksi);
            insertTransaksi.executeUpdate();

            // Ambil ID transaksi yang baru saja dibuat
            ResultSet rs = insertTransaksi.getGeneratedKeys();
            int idTransaksi = rs.next() ? rs.getInt(1) : 0;

            if (idTransaksi == 0) {
                throw new SQLException("Gagal mendapatkan ID transaksi.");
            }

            // Masukkan data ke tabel detail_transaksi dan update stok
            String insertDetailQuery = "INSERT INTO transaksi_detail (id_transaksi, id_produk, id_kasir, jumlah_produk, harga_satuan, total_harga_produk, tanggal_transaksi) VALUES (?, ?, ?, ?, ?, ?, ?)";
            String updateStokQuery = "UPDATE products SET product_stock = product_stock - ? WHERE id = ?";
            insertDetailTransaksi = K.prepareStatement(insertDetailQuery);
            updateStok = K.prepareStatement(updateStokQuery);

            for (int i = 0; i < model.getRowCount(); i++) {
                int idProduk = Integer.parseInt(model.getValueAt(i, 0).toString());
                int qty = Integer.parseInt(model.getValueAt(i, 2).toString());
                double harga = Double.parseDouble(model.getValueAt(i, 3).toString());
                double totalHargaDetail = qty * harga;

                // Masukkan detail transaksi
                insertDetailTransaksi.setInt(1, idTransaksi);
                insertDetailTransaksi.setInt(2, idProduk);
                insertDetailTransaksi.setInt(3, idKasir);
                insertDetailTransaksi.setInt(4, qty);
                insertDetailTransaksi.setDouble(5, harga);
                insertDetailTransaksi.setDouble(6, totalHargaDetail);
                insertDetailTransaksi.setString(7, tanggalTransaksi);
                insertDetailTransaksi.executeUpdate();

                // Update stok produk
                updateStok.setInt(1, qty);
                updateStok.setInt(2, idProduk);
                updateStok.executeUpdate();
            }

            // Commit transaksi
            K.commit();

            // Tampilkan nota
            nota nt = new nota(this, true);
            nt.setData(pr.getFullname(), tanggalTransaksi, idTransaksi, totalTransaksi, model, uangKembali, uangPembayaran);
            nt.setVisible(true);

            // Reset tabel keranjang
            model.setRowCount(0);
        } catch (SQLException e) {
            try {
                if (K != null) {
                    K.rollback();
                }
                JOptionPane.showMessageDialog(this, "Transaksi gagal: " + e.getMessage());
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Rollback gagal: " + ex.getMessage());
            }
        } finally {
            try {
                if (insertTransaksi != null) {
                    insertTransaksi.close();
                }
                if (insertDetailTransaksi != null) {
                    insertDetailTransaksi.close();
                }
                if (updateStok != null) {
                    updateStok.close();
                }
                if (K != null) {
                    K.setAutoCommit(true);
                    K.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Gagal menutup koneksi: " + e.getMessage());
            }
        }
    }
}
